# Problem 2
#
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# 
# Find the sum of all the even-valued terms in the sequence which do not exceed four million.

def fib(max):
  x, y = 1, 2
  while x < max:
    yield x
    x, y = y, x + y
    
print reduce(lambda x, y: x+y, [n for n in fib(4000000) if n % 2 == 0])
 